const Produitview = () => {
    return(
        <div>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias iure ea facilis vero quidem cupiditate accusantium suscipit repellat non, voluptates expedita asperiores neque doloremque voluptatem ut corporis culpa! Reprehenderit, ipsum.
            Modi quaerat aliquid non doloremque praesentium amet consequatur animi saepe, minima excepturi quibusdam. Doloribus minus qui perferendis distinctio porro consequuntur nam quia asperiores alias dolores, temporibus, laboriosam eos dolore voluptate!
            Praesentium similique quis deserunt, laboriosam, ut nemo doloribus culpa ducimus reiciendis impedit officia fugit. Fugit unde id consequuntur, repellendus ea voluptatum nostrum autem, quisquam eius quae cum qui! Perspiciatis, architecto.
            Possimus atque temporibus dicta nobis, debitis ab! Asperiores ratione quibusdam, impedit recusandae provident autem laudantium sed ut, distinctio assumenda magnam architecto corrupti, repellendus aliquam vitae! Enim accusamus hic expedita voluptas?
            A accusamus dignissimos consequatur dolor quia corrupti temporibus repudiandae, dolorum amet, nisi laudantium facilis dolore culpa animi, id ipsa. Ducimus illum et officia nostrum amet iure atque nulla accusamus ipsam!
            Aliquam magnam numquam deleniti! Repellat nemo, asperiores porro commodi molestias reiciendis molestiae provident iure earum hic ex minus nesciunt temporibus perspiciatis dolorum sapiente vero dolor et quae sint. Unde, asperiores.
            Voluptas reprehenderit dolor velit optio repellat debitis! Fugiat, eaque! Iure dolorem illum aliquid dolore rerum impedit, veritatis alias est vel pariatur voluptas aspernatur laudantium vero. Magni vel corrupti at placeat.
            Dicta consequuntur dignissimos incidunt libero culpa ratione debitis asperiores aperiam itaque ut rem magni, omnis tempore facere animi placeat, maiores et adipisci mollitia nesciunt possimus voluptates molestiae beatae! Itaque, repudiandae.
            Debitis tenetur facilis ut maiores porro esse soluta eos, facere dolor fugiat aliquid voluptates, perspiciatis accusantium dolores tempore libero vitae vero? Soluta, ipsa. Eaque mollitia repellendus fuga labore laboriosam saepe!
            Rem nulla facilis totam hic corporis laborum ipsa. Totam ipsam, nobis aliquam sequi iste temporibus praesentium officiis. Deleniti possimus, dolor eligendi ipsam fuga obcaecati quibusdam. Rem officia eum quod temporibus.
            Voluptates inventore suscipit esse dolor non. Adipisci quam delectus beatae vero unde magnam libero sit voluptate perferendis ullam. Omnis, doloremque! Esse doloribus in facilis autem! Similique at iure ratione id.
            Illum, iusto, soluta illo unde animi officiis odit veniam eos nam repudiandae sit maxime magnam recusandae dolores minus quia ad, iste voluptas. Eius impedit aperiam dolorem totam maxime obcaecati dolor.
            Id, nesciunt. Aut quam illo voluptates assumenda excepturi aliquam sunt alias officiis, fuga, asperiores aliquid temporibus? Nemo, impedit. Quis odit expedita amet. Sunt officia tenetur, quod temporibus ab incidunt quos?
            Maxime laboriosam consequuntur temporibus officiis dolor repellat quis hic dicta eaque fugiat quas consectetur ab quisquam qui animi enim ipsam, ducimus iure itaque. Labore at ut necessitatibus libero, expedita excepturi!
            Ullam, dolorem illo quisquam eius reprehenderit consequatur hic laboriosam? Soluta dolores autem tempora, natus voluptatem quod ad earum. Omnis eveniet iste eos dolorum ipsam vel esse maxime fugit! Perferendis, minima!
            Totam voluptatem debitis vitae laborum atque officiis reiciendis ullam obcaecati maxime eos suscipit nisi, deleniti sunt natus itaque dolorum, aut neque? Quaerat soluta rerum reiciendis, asperiores quidem impedit est dicta!
            Rem molestiae mollitia dolorum est ad accusamus dignissimos quasi porro adipisci dolore ullam similique sint sapiente totam ipsa magni explicabo illum, assumenda corporis, quos officia! Minima, est minus. Cupiditate, nesciunt.
            Facere officiis dolores quasi nihil ducimus deserunt pariatur natus commodi soluta culpa quia corrupti repellat cumque ullam perferendis obcaecati nam rerum molestiae, eaque exercitationem nemo blanditiis placeat dolor architecto? Nostrum!
            Dignissimos quae voluptatibus eaque delectus ab dolor eos nostrum qui perspiciatis voluptatum numquam reprehenderit, odio natus unde, aliquam sunt animi. Totam non aliquam iste velit laboriosam tenetur iure impedit? Adipisci!
            Sed laudantium rerum reprehenderit, totam similique quia velit eligendi, culpa veritatis error aperiam tempore nesciunt. Recusandae, in dolores asperiores officia ut eum fuga, illum tenetur veritatis obcaecati voluptatum eos esse?
            Quis eaque, earum dolor optio nam commodi? Recusandae dolor, cum illum labore assumenda quod, doloribus eveniet delectus voluptatum eaque corrupti nisi! Repellat fuga accusantium quibusdam porro hic at maxime quasi.
            Corrupti numquam voluptatibus autem facere quisquam sit deserunt! Magni ad quos fuga ratione? Beatae consectetur est pariatur cupiditate voluptatem! Incidunt assumenda ducimus ut delectus reiciendis dicta dolore minus aliquid odit!
            Natus maxime odit doloremque ad earum nemo autem esse ex! Magnam exercitationem unde porro animi at ad quibusdam quo, doloribus, quae harum ea consequatur dolorum, saepe earum reprehenderit qui repellendus?
            Laborum dolores, officia voluptate rerum delectus doloribus quisquam quos dolorem. Consequuntur culpa reprehenderit voluptate laborum, consequatur similique animi deleniti nisi. Sed est ea dolore aspernatur perferendis sint reprehenderit et velit?
            Dolore a possimus dolorum veniam, temporibus quos eveniet reprehenderit omnis, non doloribus labore minus amet iste exercitationem suscipit rerum corrupti fuga. Ducimus ut numquam quaerat? Consequuntur, reiciendis atque! Facilis, minima!
            Nobis esse incidunt voluptates asperiores porro accusamus commodi sapiente ad, similique, quasi error animi! Itaque, aspernatur quibusdam possimus vitae harum enim cum earum, ipsam eveniet similique eius obcaecati. Saepe, necessitatibus!
            Voluptates alias quibusdam delectus soluta eos voluptas itaque sequi et deserunt officiis explicabo excepturi atque eligendi architecto hic dolorem quaerat, accusantium modi recusandae. Molestias autem fugiat ratione sint ab modi!
            Totam illum suscipit, consequatur in magni corrupti quae sint ab perspiciatis. Cupiditate fugiat voluptas, sit, sed dignissimos eos enim suscipit saepe adipisci odit molestias delectus aut placeat illo omnis facilis.
            Reprehenderit magni iure ea deserunt? Tempora, debitis consequuntur hic molestiae et perspiciatis nisi vero sint animi cum ipsum quis asperiores veniam odit officia perferendis fugit? Vitae asperiores minus eum unde!
            Iure nobis illum inventore itaque illo autem possimus animi quidem magni esse accusamus dignissimos molestias, tempora delectus repellat laborum veritatis distinctio eos, praesentium provident perspiciatis atque expedita incidunt repudiandae. Cum!
            Inventore rerum placeat fugiat quisquam cupiditate molestias voluptatibus aperiam, obcaecati mollitia. Quo labore amet perferendis. Inventore nisi aspernatur accusamus ex tempore veritatis, earum dolores repellendus. Qui modi dolores unde tempora?
            Cum quibusdam cumque consequuntur ea libero beatae maxime, impedit aliquam maiores tempore. Tempore perspiciatis quis eaque consequuntur labore sit omnis libero temporibus ipsam? Beatae blanditiis quas atque excepturi iste corporis.
            Sed voluptatem optio totam repellendus a, veritatis accusantium cumque officiis mollitia temporibus atque repudiandae, non similique ipsam repellat in neque nostrum consequuntur? Molestias exercitationem dignissimos excepturi consequatur fugiat voluptates aspernatur?
            Ab nam vitae accusamus eligendi natus consequatur nemo ullam nesciunt corrupti id ducimus deserunt facere eaque quis, praesentium voluptas! Minus, aliquam exercitationem. Pariatur exercitationem voluptatum, iusto dolor amet reiciendis eum!
            Suscipit veniam quos odio corrupti beatae. Corporis eaque nisi doloremque porro amet saepe, ad beatae, ipsam vitae fuga autem asperiores quo! Nisi culpa sapiente asperiores est veniam! Nulla, sint repudiandae.
            Impedit eligendi repellendus sequi iure, repellat magnam? Delectus, deserunt quasi hic inventore tempora excepturi aperiam quia nemo, earum nobis recusandae. Perferendis dolorum laborum velit natus voluptates nostrum nemo hic quas.
            Facere suscipit, sint excepturi fugiat amet, modi placeat dignissimos repellendus deserunt, praesentium minima asperiores dicta impedit ut porro quibusdam voluptatem dolorem totam doloribus iure laudantium earum vero iste autem! Minima.
            Nisi quibusdam dolorum placeat, velit fuga sunt iure hic voluptates quod tempora expedita beatae aliquid fugit quaerat cumque. Ullam adipisci numquam vitae, ipsam dolore quaerat magnam libero eos earum quasi.
            Similique dolorum odit maxime nemo repudiandae officiis fugiat alias magni asperiores, impedit explicabo ipsa? Sequi beatae odit provident quibusdam, totam ex vel architecto nobis eligendi animi magni cupiditate minus. Praesentium?
            Culpa voluptas asperiores consectetur expedita enim voluptatem minus eius debitis quidem, rem nostrum dignissimos officia nesciunt laudantium soluta, quos nihil, magni delectus illum error unde. Ipsum itaque iusto earum minima!
            Laborum, obcaecati! Magnam commodi incidunt cumque, quos laudantium quas sequi iusto aperiam. Cupiditate commodi ratione iusto illum numquam quidem odio ab possimus vitae. Aliquam nam error impedit, delectus corrupti possimus.
            Deleniti quo quibusdam aut rerum architecto vel nesciunt praesentium, magnam facere commodi maxime enim dolorem possimus deserunt est? Repellendus suscipit vel, quibusdam eius in ut et rerum nemo quidem ducimus.
            In minus neque, obcaecati quis placeat nisi accusantium nesciunt ab quia totam veritatis amet ut cupiditate voluptatem optio eum odio aliquam distinctio eius quam provident iste. Cumque fugit assumenda veritatis.
            Odit hic autem repudiandae praesentium amet quas architecto labore, quia quidem est, corporis quos ad? Aperiam nisi in doloremque quis, rem qui aliquid repellat pariatur magnam vel eveniet quod odio.
            Sapiente sint nemo enim, eveniet consectetur officia. Maxime a dolorem totam officiis quasi pariatur perspiciatis expedita, harum repellat laborum cumque repellendus aut excepturi soluta dolorum nihil ea eum officia iste.
            At voluptatem neque iure doloribus hic, delectus quam beatae voluptates! Laboriosam autem incidunt, voluptatum libero repudiandae, ipsum natus, quasi dignissimos labore iusto repellendus eveniet deleniti architecto laborum voluptatibus saepe explicabo.
            Ratione tenetur molestiae rem asperiores consequuntur ducimus quasi mollitia minus odio nostrum, beatae error optio vel necessitatibus corporis dolores recusandae expedita quae dolorum sapiente. Alias voluptatum explicabo odit ratione repellendus?
            Id delectus doloremque iure dignissimos sint quidem, alias perspiciatis officia optio unde, ipsam molestiae eum in culpa omnis minus dolores at, nostrum vero deleniti iste facilis hic. Libero, autem temporibus.
            Ut similique quod quibusdam temporibus, deserunt facere assumenda reiciendis voluptas mollitia voluptates numquam, eum magni, inventore ad? Dignissimos unde quos, architecto recusandae quae facilis dolor fuga, deleniti voluptatibus, accusamus quas!
            Aperiam, dolor eveniet. Explicabo pariatur earum deleniti. Maxime odio saepe, deserunt sed excepturi quaerat! Veritatis est, totam consectetur aspernatur, perspiciatis cum laudantium dolore quibusdam nisi asperiores nesciunt ea deleniti perferendis.
        </div>
    )
}

export default Produitview